products =
{
  - !src.Model.Product
    id:       1
    name:     Montre Connectée
    brand:    Huawei
    price:    165.40
    details:  Watch GT 2 avec GPS et boîtier de 46 mm
  
  - !src.Model.Product
    id:       2
    name:     Enceinte Bluetooth
    brand:    JBL
    price:    127
    details:  Charge 4 enceinte bluetooth portable avec usb robuste et étanche

  - !src.Model.Product
    id:       3
    name:     Montre Connectée
    brand:    Apple
    price:    479
    details:  Apple Watch Series 5 (GPS 44 mm) Boîtier en Aluminium Gris Sidéral

  - !src.Model.Product
    id:       4
    name:     Enceinte
    brand:    Bose
    price:    167
    details:  Bose SoundLink Revolve Enceinte Bluetooth - Noir

  - !src.Model.Product
    id:       5
    name:     Ampoules
    brand:    Philips Lighting
    price:    64.55
    details:  Philips Hue Kit de Démarrage 3 Ampoules White E27

  - !src.Model.Product
    id:       6
    name:     Tensiomètre
    brand:    OMRON Healthcare
    price:    69.53
    details:  OMRON M7 IT Tensiomètre Électronique Brassard

  - !src.Model.Product
    id:       7
    name:     Enceinte portable
    brand:    JBL
    price:    379
    details:  JBL Boombox Enceinte Portable - Son Ultra Puissant - Modes de Son

  - !src.Model.Product
    id:       8
    name:     Ecouteurs sans fils
    brand:    AUKEY
    price:    96.67
    details:  AUKEY Écouteurs Bluetooth sans Fils - 7h d'écoute par Charge

  - !src.Model.Product
    id:       9
    name:     Mini Enceinte
    brand:    JBL
    price:    29.99
    details:  JBL GO 2 Mini Enceinte Bluetooth Portable - Étanche pour Piscine

  - !src.Model.Product
    id:       10
    name:     Montre Intelligente
    brand:    BOZLUN
    price:    54.99
    details:  Montre Intelligente Femme/Homme Moniteur de fréquence
}